//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_SUPPLIER_SITE_ALL
    {
        public int VENDOR_SITE_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public Nullable<int> LAST_UPDATED_BY { get; set; }
        public Nullable<int> VENDOR_ID { get; set; }
        public string VENDOR_SITE_CODE { get; set; }
        public string VENDOR_SITE_CODE_ALT { get; set; }
        public Nullable<int> LAST_UPDATE_LOGIN { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public string PURCHASING_SITE_FLAG { get; set; }
        public string RFQ_ONLY_SITE_FLAG { get; set; }
        public string PAY_SITE_FLAG { get; set; }
        public string ATTENTION_AR_FLAG { get; set; }
        public string ADDRESS_LINE1 { get; set; }
        public string ADDRESS_LINES_ALT { get; set; }
        public string ADDRESS_LINE2 { get; set; }
        public string ADDRESS_LINE3 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public string PROVINCE { get; set; }
        public string COUNTRY { get; set; }
        public string AREA_CODE { get; set; }
        public string PHONE { get; set; }
        public string CUSTOMER_NUM { get; set; }
        public Nullable<int> SHIP_TO_LOCATION_ID { get; set; }
        public Nullable<int> BILL_TO_LOCATION_ID { get; set; }
        public string SHIP_VIA_LOOKUP_CODE { get; set; }
        public string FREIGHT_TERMS_LOOKUP_CODE { get; set; }
        public string FOB_LOOKUP_CODE { get; set; }
        public Nullable<System.DateTime> INACTIVE_DATE { get; set; }
        public string FAX { get; set; }
        public string FAX_AREA_CODE { get; set; }
        public string TELEX { get; set; }
        public string PAYMENT_METHOD_LOOKUP_CODE { get; set; }
        public string BANK_ACCOUNT_NAME { get; set; }
        public string BANK_ACCOUNT_NUM { get; set; }
        public string BANK_NUM { get; set; }
        public string BANK_ACCOUNT_TYPE { get; set; }
        public string TERMS_DATE_BASIS { get; set; }
        public string CURRENT_CATALOG_NUM { get; set; }
        public string VAT_CODE { get; set; }
        public Nullable<int> DISTRIBUTION_SET_ID { get; set; }
        public Nullable<int> ACCTS_PAY_CODE_COMBINATION_ID { get; set; }
        public Nullable<int> PREPAY_CODE_COMBINATION_ID { get; set; }
        public string PAY_GROUP_LOOKUP_CODE { get; set; }
        public Nullable<int> PAYMENT_PRIORITY { get; set; }
        public Nullable<int> TERMS_ID { get; set; }
        public Nullable<int> INVOICE_AMOUNT_LIMIT { get; set; }
        public string PAY_DATE_BASIS_LOOKUP_CODE { get; set; }
        public string ALWAYS_TAKE_DISC_FLAG { get; set; }
        public string INVOICE_CURRENCY_CODE { get; set; }
        public string PAYMENT_CURRENCY_CODE { get; set; }
        public string HOLD_ALL_PAYMENTS_FLAG { get; set; }
        public string HOLD_FUTURE_PAYMENTS_FLAG { get; set; }
        public string HOLD_REASON { get; set; }
        public string HOLD_UNMATCHED_INVOICES_FLAG { get; set; }
        public string AP_TAX_ROUNDING_RULE { get; set; }
        public string AUTO_TAX_CALC_FLAG { get; set; }
        public string AUTO_TAX_CALC_OVERRIDE { get; set; }
        public string AMOUNT_INCLUDES_TAX_FLAG { get; set; }
        public string EXCLUSIVE_PAYMENT_FLAG { get; set; }
        public string TAX_REPORTING_SITE_FLAG { get; set; }
        public string ATTRIBUTE_CATEGORY { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
        public string ATTRIBUTE6 { get; set; }
        public string ATTRIBUTE7 { get; set; }
        public string ATTRIBUTE8 { get; set; }
        public string ATTRIBUTE9 { get; set; }
        public string ATTRIBUTE10 { get; set; }
        public string ATTRIBUTE11 { get; set; }
        public string ATTRIBUTE12 { get; set; }
        public string ATTRIBUTE13 { get; set; }
        public string ATTRIBUTE14 { get; set; }
        public string ATTRIBUTE15 { get; set; }
        public Nullable<int> REQUEST_ID { get; set; }
        public Nullable<int> PROGRAM_APPLICATION_ID { get; set; }
        public Nullable<int> PROGRAM_ID { get; set; }
        public Nullable<System.DateTime> PROGRAM_UPDATE_DATE { get; set; }
        public Nullable<int> VALIDATION_NUMBER { get; set; }
        public string EXCLUDE_FREIGHT_FROM_DISCOUNT { get; set; }
        public string VAT_REGISTRATION_NUM { get; set; }
        public string OFFSET_VAT_CODE { get; set; }
        public Nullable<int> ORG_ID { get; set; }
        public string CHECK_DIGITS { get; set; }
        public string BANK_NUMBER { get; set; }
        public string ADDRESS_LINE4 { get; set; }
        public string COUNTY { get; set; }
        public string ADDRESS_STYLE { get; set; }
        public string LANGUAGE { get; set; }
        public string ALLOW_AWT_FLAG { get; set; }
        public Nullable<int> AWT_GROUP_ID { get; set; }
        public string GLOBAL_ATTRIBUTE1 { get; set; }
        public string GLOBAL_ATTRIBUTE2 { get; set; }
        public string GLOBAL_ATTRIBUTE3 { get; set; }
        public string GLOBAL_ATTRIBUTE4 { get; set; }
        public string GLOBAL_ATTRIBUTE5 { get; set; }
        public string GLOBAL_ATTRIBUTE6 { get; set; }
        public string GLOBAL_ATTRIBUTE7 { get; set; }
        public string GLOBAL_ATTRIBUTE8 { get; set; }
        public string GLOBAL_ATTRIBUTE9 { get; set; }
        public string GLOBAL_ATTRIBUTE10 { get; set; }
        public string GLOBAL_ATTRIBUTE11 { get; set; }
        public string GLOBAL_ATTRIBUTE12 { get; set; }
        public string GLOBAL_ATTRIBUTE13 { get; set; }
        public string GLOBAL_ATTRIBUTE14 { get; set; }
        public string GLOBAL_ATTRIBUTE15 { get; set; }
        public string GLOBAL_ATTRIBUTE16 { get; set; }
        public string GLOBAL_ATTRIBUTE17 { get; set; }
        public string GLOBAL_ATTRIBUTE18 { get; set; }
        public string GLOBAL_ATTRIBUTE19 { get; set; }
        public string GLOBAL_ATTRIBUTE20 { get; set; }
        public string GLOBAL_ATTRIBUTE_CATEGORY { get; set; }
        public string EDI_TRANSACTION_HANDLING { get; set; }
        public string EDI_ID_NUMBER { get; set; }
        public string EDI_PAYMENT_METHOD { get; set; }
        public string EDI_PAYMENT_FORMAT { get; set; }
        public string EDI_REMITTANCE_METHOD { get; set; }
        public string BANK_CHARGE_BEARER { get; set; }
        public string EDI_REMITTANCE_INSTRUCTION { get; set; }
        public string BANK_BRANCH_TYPE { get; set; }
        public string PAY_ON_CODE { get; set; }
        public Nullable<int> DEFAULT_PAY_SITE_ID { get; set; }
        public string PAY_ON_RECEIPT_SUMMARY_CODE { get; set; }
        public Nullable<int> TP_HEADER_ID { get; set; }
        public string ECE_TP_LOCATION_CODE { get; set; }
        public string PCARD_SITE_FLAG { get; set; }
        public string MATCH_OPTION { get; set; }
        public string COUNTRY_OF_ORIGIN_CODE { get; set; }
        public Nullable<int> FUTURE_DATED_PAYMENT_CCID { get; set; }
        public string CREATE_DEBIT_MEMO_FLAG { get; set; }
        public string OFFSET_TAX_FLAG { get; set; }
        public string SUPPLIER_NOTIF_METHOD { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public string REMITTANCE_EMAIL { get; set; }
        public string PRIMARY_PAY_SITE_FLAG { get; set; }
        public string SHIPPING_CONTROL { get; set; }
        public string SELLING_COMPANY_IDENTIFIER { get; set; }
        public string GAPLESS_INV_NUM_FLAG { get; set; }
        public string DUNS_NUMBER { get; set; }
        public Nullable<int> TOLERANCE_ID { get; set; }
        public Nullable<int> LOCATION_ID { get; set; }
        public Nullable<int> PARTY_SITE_ID { get; set; }
        public Nullable<int> SERVICES_TOLERANCE_ID { get; set; }
        public Nullable<int> RETAINAGE_RATE { get; set; }
        public string TCA_SYNC_STATE { get; set; }
        public string TCA_SYNC_PROVINCE { get; set; }
        public string TCA_SYNC_COUNTY { get; set; }
        public string TCA_SYNC_CITY { get; set; }
        public string TCA_SYNC_ZIP { get; set; }
        public string TCA_SYNC_COUNTRY { get; set; }
        public Nullable<int> PAY_AWT_GROUP_ID { get; set; }
        public string CAGE_CODE { get; set; }
        public string LEGAL_BUSINESS_NAME { get; set; }
        public string DOING_BUS_AS_NAME { get; set; }
        public string DIVISION_NAME { get; set; }
        public string SMALL_BUSINESS_CODE { get; set; }
        public string CCR_COMMENTS { get; set; }
        public Nullable<System.DateTime> DEBARMENT_START_DATE { get; set; }
        public Nullable<System.DateTime> DEBARMENT_END_DATE { get; set; }
    }
}
