//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BFB_ADJUST_FACTOR_HEADER
    {
        public double HEADER_ID_PK { get; set; }
        public string DOCUMENT_NO { get; set; }
        public Nullable<System.DateTime> DOCUMENT_DATE { get; set; }
        public string APPROVAL_STATUS { get; set; }
        public string ADJUST_TYPE { get; set; }
        public string ADJUST_TYPE_CODE { get; set; }
        public Nullable<double> ADJUST_TYPE_ID { get; set; }
        public string FACTOR { get; set; }
        public string FACTOR_CODE { get; set; }
        public Nullable<double> FACTOR_ID { get; set; }
        public string ADJUST_PERIOD_TYPE { get; set; }
        public string ADJ_PER_TYPE_CODE { get; set; }
        public Nullable<double> ADJUST_PER_TYPE_ID { get; set; }
        public string ADJUST_PERIOD { get; set; }
        public Nullable<double> ADJUST_PERIOD_ID { get; set; }
        public string BILLING_MONTH { get; set; }
        public Nullable<double> BILLING_MONTH_ID { get; set; }
        public Nullable<double> ADJUST_RATE { get; set; }
        public Nullable<double> ADJUST_AMOUNT { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
        public string ATTRIBUTE6 { get; set; }
        public string ATTRIBUTE7 { get; set; }
        public string ATTRIBUTE8 { get; set; }
        public string ATTRIBUTE9 { get; set; }
        public string ATTRIBUTE10 { get; set; }
        public Nullable<double> ORGANIZATION_ID { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<double> CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public Nullable<double> LAST_UPDATED_BY { get; set; }
        public Nullable<double> LAST_UPDATE_LOGIN { get; set; }
        public Nullable<System.DateTime> DATE_FROM { get; set; }
        public Nullable<System.DateTime> DATE_TO { get; set; }
    }
}
