//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BFBINVOICE_LINE
    {
        public double LINE_ID_PK { get; set; }
        public Nullable<double> HEADER_ID_FK { get; set; }
        public Nullable<double> KWH_TOTAL { get; set; }
        public Nullable<double> KVARH_TOTAL { get; set; }
        public Nullable<double> MDI_TOTAL { get; set; }
        public Nullable<double> POWER_FACTOR { get; set; }
        public Nullable<double> LPF { get; set; }
        public Nullable<double> NJ_FUND_RATE { get; set; }
        public Nullable<double> NJ_FUND_AMOUNT { get; set; }
        public Nullable<double> VC_RATE { get; set; }
        public Nullable<double> VC_AMOUNT { get; set; }
        public Nullable<double> TRS_RATE { get; set; }
        public Nullable<double> TRS_AMOUNT { get; set; }
        public Nullable<double> FC_RATE { get; set; }
        public Nullable<double> FC_AMOUNT { get; set; }
        public Nullable<double> LPF_PENALTY_RATE { get; set; }
        public Nullable<double> LPF_PENALTY_AMOUNT { get; set; }
        public Nullable<double> FCS_RATE { get; set; }
        public Nullable<double> FCS_AMOUNT { get; set; }
        public Nullable<double> FPA_RATE_TOTAL { get; set; }
        public Nullable<double> FPA_AMOUNT_TOTAL { get; set; }
        public Nullable<double> ED_RATE_TOTAL { get; set; }
        public Nullable<double> ED_AMOUNT_TOTAL { get; set; }
        public Nullable<double> GST_RATE_TOTAL { get; set; }
        public Nullable<double> GST_AMOUNT_TOTAL { get; set; }
        public Nullable<double> ARREAR_BILL_ADJ { get; set; }
        public Nullable<double> CURRENT_BILL { get; set; }
        public Nullable<double> BILL_PAYABLE { get; set; }
        public Nullable<double> LPS { get; set; }
        public Nullable<double> GST_LPS { get; set; }
        public Nullable<double> BILL_PAYABLE_AFTER { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<double> CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public Nullable<double> LAST_UPDATED_BY { get; set; }
        public Nullable<double> LAST_UPDATE_LOGIN { get; set; }
    }
}
