//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BFBINVOICE_DETAIL
    {
        public double DETAIL_ID_PK { get; set; }
        public Nullable<double> LINE_ID_FK { get; set; }
        public Nullable<double> FPA_RATE { get; set; }
        public Nullable<double> FPA_AMOUNT { get; set; }
        public Nullable<double> ED_RATE { get; set; }
        public Nullable<double> ED_AMOUNT { get; set; }
        public Nullable<double> GST_RATE { get; set; }
        public Nullable<double> GST_AMOUNT { get; set; }
        public string BILL_MONTH { get; set; }
        public Nullable<double> BILL_MONTH_ID { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<double> CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public Nullable<double> LAST_UPDATED_BY { get; set; }
        public Nullable<double> LAST_UPDATE_LOGIN { get; set; }
        public Nullable<double> ENERGY_BILLED { get; set; }
    }
}
