//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPI_RATES
    {
        public double CPI_ID_PK { get; set; }
        public Nullable<double> HEADER_ID_FK { get; set; }
        public Nullable<double> CURRENCY_ID_FK { get; set; }
        public string CPI_TYPE { get; set; }
        public Nullable<double> JAN { get; set; }
        public Nullable<double> FEB { get; set; }
        public Nullable<double> MAR { get; set; }
        public Nullable<double> APR { get; set; }
        public Nullable<double> MAY { get; set; }
        public Nullable<double> JUN { get; set; }
        public Nullable<double> JUL { get; set; }
        public Nullable<double> AUG { get; set; }
        public Nullable<double> SEP { get; set; }
        public Nullable<double> OCT { get; set; }
        public Nullable<double> NOV { get; set; }
        public Nullable<double> DECE { get; set; }
        public string REMARKS { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
        public string ATTRIBUTE6 { get; set; }
        public string ATTRIBUTE7 { get; set; }
        public string ATTRIBUTE8 { get; set; }
        public string ATTRIBUTE9 { get; set; }
        public string ATTRIBUTE10 { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<double> CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public Nullable<double> LAST_UPDATED_BY { get; set; }
        public Nullable<double> LAST_UPDATE_LOGIN { get; set; }
    }
}
