//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRS_INV_DETAIL
    {
        public double DET_ID_PK { get; set; }
        public Nullable<double> BLK_FUEL_ID_FK { get; set; }
        public Nullable<double> HEADER_ID_FK { get; set; }
        public string COLUMN1 { get; set; }
        public string COLUMN2 { get; set; }
        public string COLUMN3 { get; set; }
        public string COLUMN4 { get; set; }
        public string COLUMN5 { get; set; }
        public string COLUMN6 { get; set; }
        public string COLUMN7 { get; set; }
        public string COLUMN8 { get; set; }
        public string COLUMN9 { get; set; }
        public string COLUMN10 { get; set; }
        public string COLUMN11 { get; set; }
        public string COLUMN12 { get; set; }
        public string COLUMN13 { get; set; }
        public string COLUMN14 { get; set; }
        public string COLUMN15 { get; set; }
        public string COLUMN16 { get; set; }
        public string COLUMN17 { get; set; }
        public string COLUMN18 { get; set; }
        public string COLUMN19 { get; set; }
        public string COLUMN20 { get; set; }
        public string COLUMN21 { get; set; }
        public string COLUMN22 { get; set; }
        public string COLUMN23 { get; set; }
        public string COLUMN24 { get; set; }
        public string COLUMN25 { get; set; }
        public string COLUMN26 { get; set; }
        public string COLUMN27 { get; set; }
        public string COLUMN28 { get; set; }
        public string COLUMN29 { get; set; }
        public string COLUMN30 { get; set; }
        public string COLUMN31 { get; set; }
        public string COLUMN32 { get; set; }
        public string COLUMN33 { get; set; }
        public string COLUMN34 { get; set; }
        public string COLUMN35 { get; set; }
        public string COLUMN36 { get; set; }
        public string COLUMN37 { get; set; }
        public string COLUMN38 { get; set; }
        public string COLUMN39 { get; set; }
        public string COLUMN40 { get; set; }
        public string COLUMN41 { get; set; }
        public string COLUMN42 { get; set; }
        public string COLUMN43 { get; set; }
        public string COLUMN44 { get; set; }
        public string COLUMN45 { get; set; }
        public string COLUMN46 { get; set; }
        public string COLUMN47 { get; set; }
        public string COLUMN48 { get; set; }
        public string COLUMN49 { get; set; }
        public string COLUMN50 { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<double> CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public Nullable<double> LAST_UPDATED_BY { get; set; }
        public Nullable<double> LAST_UPDATE_LOGIN { get; set; }
    }
}
