//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICE
    {
        public double HEADER_ID_PK { get; set; }
        public string DOCUMENT_NO { get; set; }
        public Nullable<System.DateTime> DOCUMENT_DATE { get; set; }
        public Nullable<double> EVENT_TRK_ID_FK { get; set; }
        public string POWER_POLICY { get; set; }
        public Nullable<double> VENDOR_ID_FK { get; set; }
        public Nullable<double> VENDOR_SITE_ID_FK { get; set; }
        public string INV_TYPE { get; set; }
        public Nullable<double> DOC_REC_ID_FK { get; set; }
        public string VENDOR_INV_NO { get; set; }
        public Nullable<System.DateTime> ELEC_INV_REC_DT { get; set; }
        public Nullable<System.DateTime> FINAL_INV_REC_DT { get; set; }
        public string CURR_AGG_YEAR { get; set; }
        public Nullable<System.DateTime> INV_PERIOD_FRM { get; set; }
        public Nullable<System.DateTime> INV_PERIOD_TO { get; set; }
        public string DUE_DT_TERM { get; set; }
        public Nullable<System.DateTime> INV_DUE_DT { get; set; }
        public string APPROVAL_STATUS { get; set; }
        public string REMARKS { get; set; }
        public Nullable<double> PPA_ID_FK { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
        public string ATTRIBUTE6 { get; set; }
        public string ATTRIBUTE7 { get; set; }
        public string ATTRIBUTE8 { get; set; }
        public string ATTRIBUTE9 { get; set; }
        public string ATTRIBUTE10 { get; set; }
        public Nullable<double> ORGANIZATION_ID { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<double> CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public Nullable<double> LAST_UPDATED_BY { get; set; }
        public Nullable<double> LAST_UPDATE_LOGIN { get; set; }
        public Nullable<double> TOT_EXC_GST { get; set; }
        public Nullable<double> GST_PER { get; set; }
        public Nullable<double> GST_AMOUNT { get; set; }
        public Nullable<double> TOT_INC_GST { get; set; }
        public Nullable<double> TOT_EXC_GST_CL { get; set; }
        public Nullable<double> GST_PER_CL { get; set; }
        public Nullable<double> GST_AMOUNT_CL { get; set; }
        public Nullable<double> TOT_INC_GST_CL { get; set; }
        public Nullable<double> REN_NED { get; set; }
        public Nullable<double> REN_NPMV { get; set; }
        public Nullable<double> REN_NEOTOTAL { get; set; }
        public Nullable<double> REN_NDE_CLAIM { get; set; }
        public Nullable<double> REN_NPMV_CLAIM { get; set; }
        public Nullable<double> REN_NEOCLAIM_TOTAL { get; set; }
        public Nullable<System.DateTime> GL_DATE { get; set; }
        public string IS_HOURLY { get; set; }
        public Nullable<double> DIFF_EXC_GST { get; set; }
        public Nullable<double> DIFF_GST_PER { get; set; }
        public Nullable<double> DIFF_GST_AMOUNT { get; set; }
        public Nullable<double> DIFF_INC_GST { get; set; }
        public string INTERFACE_STATUS { get; set; }
        public Nullable<double> DUE_DATE_TOLRNCE { get; set; }
        public Nullable<System.DateTime> FINAL_DUE_DT { get; set; }
        public string INITIATOR_REMARKS { get; set; }
        public string IS_DIFFERENTIAL { get; set; }
        public Nullable<double> PARENT_INV_AMOUNT { get; set; }
        public Nullable<double> COMPOUNDING_DAYS { get; set; }
        public Nullable<System.DateTime> CANCEL_DATE { get; set; }
    }
}
