//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICE_DISCO_BILL_L_T
    {
        public double LINE_ID_PK { get; set; }
        public Nullable<double> HEADER_ID_FK { get; set; }
        public string DISCO_NAME { get; set; }
        public Nullable<double> UOSC_FIXED_RATE { get; set; }
        public Nullable<double> UOSC_FIXED_AMOUNT { get; set; }
        public Nullable<double> UOSC_TOTAL { get; set; }
        public Nullable<double> CTC { get; set; }
        public Nullable<double> ETC { get; set; }
        public Nullable<double> TTC { get; set; }
        public Nullable<double> GST { get; set; }
        public Nullable<double> PAYABLE { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
        public string ATTRIBUTE6 { get; set; }
        public string ATTRIBUTE7 { get; set; }
        public string ATTRIBUTE8 { get; set; }
        public string ATTRIBUTE9 { get; set; }
        public string ATTRIBUTE10 { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<double> CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public Nullable<double> LAST_UPDATED_BY { get; set; }
        public Nullable<double> LAST_UPDATE_LOGIN { get; set; }
        public Nullable<double> UOSC_VAR_RATE { get; set; }
        public Nullable<double> UOSC_VAR_AMOUNT { get; set; }
        public Nullable<double> CTC_RATE { get; set; }
        public Nullable<double> ETC_RATE { get; set; }
    }
}
