//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDI_ACT_REACT_EN_HEADER
    {
        public double HEADER_ID_PK { get; set; }
        public string DOCUMENT_NO { get; set; }
        public Nullable<System.DateTime> DOCUMENT_DATE { get; set; }
        public string APPROVAL_STATUS { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
        public string ATTRIBUTE6 { get; set; }
        public string ATTRIBUTE7 { get; set; }
        public string ATTRIBUTE8 { get; set; }
        public string ATTRIBUTE9 { get; set; }
        public string ATTRIBUTE10 { get; set; }
        public Nullable<double> ORGANIZATION_ID { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<double> CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public Nullable<double> LAST_UPDATED_BY { get; set; }
        public Nullable<double> LAST_UPDATE_LOGIN { get; set; }
        public string DOC_MONTH { get; set; }
        public string IPP_NAME { get; set; }
        public Nullable<double> IPP_ID { get; set; }
        public Nullable<double> DOC_MONTH_ID { get; set; }
        public Nullable<double> MDI_TOTAL { get; set; }
        public Nullable<double> AC_KWH_TOTAL { get; set; }
        public Nullable<double> REAC_KVARH_TOTAL { get; set; }
        public Nullable<double> ADJ_AMOUNT { get; set; }
        public Nullable<double> ACTIVE_ADJ_AMOUNT { get; set; }
        public Nullable<double> RE_ACTIVE_ADJ_AMOUNT { get; set; }
        public Nullable<double> VENDOR_SITE_ID_FK { get; set; }
    }
}
