//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CPPA_DBEntities : DbContext
    {
        public CPPA_DBEntities()
            : base("name=CPPA_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AP_SUPPLIERS> AP_SUPPLIERS { get; set; }
        public DbSet<APP_SUPPLIER_SITE_ALL> APP_SUPPLIER_SITE_ALL { get; set; }
        public DbSet<BFB_ADJUST_FACTOR_HEADER> BFB_ADJUST_FACTOR_HEADER { get; set; }
        public DbSet<BFB_ADJUST_FACTOR_LINE> BFB_ADJUST_FACTOR_LINE { get; set; }
        public DbSet<BFB_RATES_MAINT> BFB_RATES_MAINT { get; set; }
        public DbSet<BFB_RATES_MAINT_L> BFB_RATES_MAINT_L { get; set; }
        public DbSet<BFBINVOICE_DETAIL> BFBINVOICE_DETAIL { get; set; }
        public DbSet<BFBINVOICE_HEADER> BFBINVOICE_HEADER { get; set; }
        public DbSet<BFBINVOICE_LINE> BFBINVOICE_LINE { get; set; }
        public DbSet<CPI_RATES> CPI_RATES { get; set; }
        public DbSet<CPPA_USER_ACCESS_HDR> CPPA_USER_ACCESS_HDR { get; set; }
        public DbSet<CPPA_USER_ACCESS_LINES> CPPA_USER_ACCESS_LINES { get; set; }
        public DbSet<DOC_REC_ADJUSTMENT> DOC_REC_ADJUSTMENT { get; set; }
        public DbSet<DOC_RECEIVING_CLAIMS> DOC_RECEIVING_CLAIMS { get; set; }
        public DbSet<DOC_RECEIVING_DEPTS_USERS> DOC_RECEIVING_DEPTS_USERS { get; set; }
        public DbSet<DOC_RECEIVING_HEADER> DOC_RECEIVING_HEADER { get; set; }
        public DbSet<DOCREC_BLKSFUEL> DOCREC_BLKSFUEL { get; set; }
        public DbSet<DOCREC_COMPS> DOCREC_COMPS { get; set; }
        public DbSet<EVENT_TRACK_HEADERS> EVENT_TRACK_HEADERS { get; set; }
        public DbSet<EVENT_TRACKS_DETAIL> EVENT_TRACKS_DETAIL { get; set; }
        public DbSet<EXCH_RATES> EXCH_RATES { get; set; }
        public DbSet<EXCRATES_CPI_CURRENCY> EXCRATES_CPI_CURRENCY { get; set; }
        public DbSet<EXCRATES_CPI_HEADER> EXCRATES_CPI_HEADER { get; set; }
        public DbSet<FORCE_MAJEOURE_HEADER> FORCE_MAJEOURE_HEADER { get; set; }
        public DbSet<FORCE_MAJEOURE_LINE> FORCE_MAJEOURE_LINE { get; set; }
        public DbSet<HRS_INV_DETAIL> HRS_INV_DETAIL { get; set; }
        public DbSet<INTEREST_DETAILS> INTEREST_DETAILS { get; set; }
        public DbSet<INV_ADJUSTMENT> INV_ADJUSTMENT { get; set; }
        public DbSet<INV_BLKS_FUELS> INV_BLKS_FUELS { get; set; }
        public DbSet<INV_COMPS> INV_COMPS { get; set; }
        public DbSet<INV_DIFF_PARENT> INV_DIFF_PARENT { get; set; }
        public DbSet<INV_HEADERS_TL> INV_HEADERS_TL { get; set; }
        public DbSet<INV_LINES_TL> INV_LINES_TL { get; set; }
        public DbSet<INV_RATES_TL> INV_RATES_TL { get; set; }
        public DbSet<INVOICE> INVOICEs { get; set; }
        public DbSet<INVOICE_DISCO_BILL_D_T> INVOICE_DISCO_BILL_D_T { get; set; }
        public DbSet<INVOICE_DISCO_BILL_H_T> INVOICE_DISCO_BILL_H_T { get; set; }
        public DbSet<INVOICE_DISCO_BILL_L_T> INVOICE_DISCO_BILL_L_T { get; set; }
        public DbSet<MDI_ACT_REACT_EN_HEADER> MDI_ACT_REACT_EN_HEADER { get; set; }
        public DbSet<MDI_ACT_REACT_EN_LINE> MDI_ACT_REACT_EN_LINE { get; set; }
        public DbSet<MDINEO_HEADER> MDINEO_HEADER { get; set; }
        public DbSet<MDINEO_LINE> MDINEO_LINE { get; set; }
        public DbSet<PPA_APPLICABLE_INVOICES> PPA_APPLICABLE_INVOICES { get; set; }
        public DbSet<PPA_BLOCKS_FUELS> PPA_BLOCKS_FUELS { get; set; }
        public DbSet<PPA_COMP_DEFS> PPA_COMP_DEFS { get; set; }
        public DbSet<PPA_HEADER> PPA_HEADER { get; set; }
        public DbSet<PPA_HEADER_INTERFACE> PPA_HEADER_INTERFACE { get; set; }
        public DbSet<PPA_RENEW_FACT> PPA_RENEW_FACT { get; set; }
        public DbSet<PPA_SLABS> PPA_SLABS { get; set; }
        public DbSet<PRESENT_RATE_INV_TYPE> PRESENT_RATE_INV_TYPE { get; set; }
        public DbSet<PRESENT_RATE_LINES> PRESENT_RATE_LINES { get; set; }
        public DbSet<PRESENT_RATES_HEADER> PRESENT_RATES_HEADER { get; set; }
        public DbSet<PRIMARY_INVOICE> PRIMARY_INVOICE { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<REF_TRF_AGREEMENT_YEARS> REF_TRF_AGREEMENT_YEARS { get; set; }
        public DbSet<REF_TRF_COMPONENTS_VAL> REF_TRF_COMPONENTS_VAL { get; set; }
        public DbSet<REF_TRF_FUEL_BLOCK> REF_TRF_FUEL_BLOCK { get; set; }
        public DbSet<REF_TRF_INV_TYPE> REF_TRF_INV_TYPE { get; set; }
        public DbSet<REFERENCE_TARIFF_HEADERS> REFERENCE_TARIFF_HEADERS { get; set; }
        public DbSet<SUP_LIB_H_T> SUP_LIB_H_T { get; set; }
        public DbSet<SUP_LIB_T> SUP_LIB_T { get; set; }
        public DbSet<UOSC_RATES_MAINT> UOSC_RATES_MAINT { get; set; }
        public DbSet<WF_HEADER> WF_HEADER { get; set; }
        public DbSet<WF_LINES> WF_LINES { get; set; }
        public DbSet<ApiUser> ApiUsers { get; set; }
        public DbSet<Token> Tokens { get; set; }
    }
}
