//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PPA_HEADER_INTERFACE
    {
        public double HEADER_ID_PK { get; set; }
        public string DOCUMENT_NO { get; set; }
        public Nullable<System.DateTime> DOCUMENT_DATE { get; set; }
        public string POWER_POLICY { get; set; }
        public Nullable<double> VENDOR_ID_FK { get; set; }
        public Nullable<double> VENDOR_SITE_ID_FK { get; set; }
        public Nullable<double> CONTRACTED_CAPACITY { get; set; }
        public Nullable<System.DateTime> AGREEMENT_DATE { get; set; }
        public Nullable<System.DateTime> FINANCIAL_CLOSE_DATE { get; set; }
        public Nullable<System.DateTime> REQUIRED_COD { get; set; }
        public Nullable<System.DateTime> ACTUAL_COD { get; set; }
        public Nullable<double> FORCE_MAJEURE { get; set; }
        public Nullable<System.DateTime> ACHIEVED_COD { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_FROM { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_TO { get; set; }
        public string DUE_DATE_TOLERANCE { get; set; }
        public string APPLY_SLAB { get; set; }
        public string APPROVAL_STATUS { get; set; }
        public string REMARKS { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<double> CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public Nullable<double> LAST_UPDATED_BY { get; set; }
        public Nullable<double> LAST_UPDATE_LOGIN { get; set; }
        public Nullable<double> ORGANIZATION_ID { get; set; }
        public string INVENTORY_COSTING_METHOD { get; set; }
        public Nullable<double> BENCHMARK_PER { get; set; }
        public Nullable<double> PARENT_DOCUMENT { get; set; }
    }
}
