//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRIMARY_INVOICE
    {
        public double PRIM_INV_ID_PK { get; set; }
        public Nullable<double> HEADER_ID_FK { get; set; }
        public Nullable<double> INV_ID_FK { get; set; }
        public string COMP_ALLOW { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<double> CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public Nullable<double> LAST_UPDATED_BY { get; set; }
        public Nullable<double> LAST_UPDATE_LOGIN { get; set; }
        public Nullable<System.DateTime> INV_PERIOD_FRM { get; set; }
        public Nullable<System.DateTime> INV_PERIOD_TO { get; set; }
        public Nullable<double> TOT_INC_GST_CL { get; set; }
        public Nullable<double> TOT_INC_GST { get; set; }
        public Nullable<double> TOTAL { get; set; }
        public Nullable<double> TOTAL_INV_AMT { get; set; }
        public string CALC_ON_DUE_DATE { get; set; }
        public string IPP_INV_NO { get; set; }
        public string REMARKS { get; set; }
        public Nullable<double> CLAIMED { get; set; }
        public Nullable<double> VERIFIED { get; set; }
    }
}
