//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class REF_TRF_FUEL_BLOCK
    {
        public double BLK_LINE_ID_PK { get; set; }
        public Nullable<double> LINE_ID_FK { get; set; }
        public Nullable<double> HEADER_ID_FK { get; set; }
        public string BLOCK_NO { get; set; }
        public string FUEL { get; set; }
        public string REMARKS { get; set; }
        public string BLK_ATTRIBUTE1 { get; set; }
        public string BLK_ATTRIBUTE2 { get; set; }
        public string BLK_ATTRIBUTE3 { get; set; }
        public string BLK_ATTRIBUTE4 { get; set; }
        public string BLK_ATTRIBUTE5 { get; set; }
        public string BLK_ATTRIBUTE6 { get; set; }
        public string BLK_ATTRIBUTE7 { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public Nullable<double> LAST_UPDATED_BY { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<double> CREATED_BY { get; set; }
        public Nullable<double> LAST_UPDATE_LOGIN { get; set; }
        public Nullable<double> ORGANIZATION_ID { get; set; }
        public Nullable<double> PPA_BLK_FUEL_ID_FK { get; set; }
    }
}
