//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class REF_TRF_AGREEMENT_YEARS
    {
        public double LINE_AGR_YR_ID_PK { get; set; }
        public Nullable<double> BLK_LINE_ID_FK { get; set; }
        public Nullable<double> HEADER_ID_FK { get; set; }
        public string AGREEMENT_YEAR { get; set; }
        public string AGR_ATTRIBUTE1 { get; set; }
        public string AGR_ATTRIBUTE2 { get; set; }
        public string AGR_ATTRIBUTE3 { get; set; }
        public string AGR_ATTRIBUTE4 { get; set; }
        public string AGR_ATTRIBUTE5 { get; set; }
        public string AGR_ATTRIBUTE6 { get; set; }
        public string AGR_ATTRIBUTE7 { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public Nullable<double> LAST_UPDATED_BY { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<double> CREATED_BY { get; set; }
        public Nullable<double> LAST_UPDATE_LOGIN { get; set; }
        public Nullable<double> ORGANIZATION_ID { get; set; }
        public string HALF_YEAR { get; set; }
        public Nullable<System.DateTime> PERIOD_FROM { get; set; }
        public Nullable<System.DateTime> PERIOD_TO { get; set; }
    }
}
