//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUP_LIB_H_T
    {
        public double HEADER_ID_FK { get; set; }
        public string DOCUMENT_NO { get; set; }
        public Nullable<System.DateTime> DOCUMENT_DATE { get; set; }
        public Nullable<double> AVAILABLE_BAL { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_DATE { get; set; }
        public string APPROVAL_STATUS { get; set; }
        public string REMARKS { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
        public string ATTRIBUTE6 { get; set; }
        public string ATTRIBUTE7 { get; set; }
        public string ATTRIBUTE8 { get; set; }
        public string ATTRIBUTE9 { get; set; }
        public string ATTRIBUTE10 { get; set; }
        public Nullable<double> ORGANIZATION_ID { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<double> CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public Nullable<double> LAST_UPDATED_BY { get; set; }
        public Nullable<double> LAST_UPDATE_LOGIN { get; set; }
        public Nullable<double> REM_BANK_BAL { get; set; }
        public Nullable<double> REM_SUP_BAL { get; set; }
        public Nullable<double> ALLOC_EPP { get; set; }
        public Nullable<double> ALLOC_CPP { get; set; }
        public Nullable<double> ALLOC_INT { get; set; }
        public Nullable<double> ALLOC_OTHER { get; set; }
        public Nullable<double> ALLOC_MAN_TOTAL { get; set; }
        public Nullable<double> REM_AVLBLE { get; set; }
        public Nullable<double> CPPA_BAL { get; set; }
        public string PARENT_DOCUMENT { get; set; }
    }
}
