//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUP_LIB_T
    {
        public double HEADER_ID_PK { get; set; }
        public string DOCUMENT_NO { get; set; }
        public Nullable<System.DateTime> DOCUMENT_DATE { get; set; }
        public string SUP_TYPE { get; set; }
        public Nullable<double> SUP_NO { get; set; }
        public string SUP_NAME { get; set; }
        public Nullable<double> PREV_YEAR_BAL { get; set; }
        public Nullable<double> VERI_INV_DUR_PER { get; set; }
        public Nullable<double> PAID_INV { get; set; }
        public Nullable<double> OUTS_AMOUNT { get; set; }
        public Nullable<double> CLOSING_BAL { get; set; }
        public Nullable<double> PRE_ALL_AMOUNT { get; set; }
        public Nullable<double> PRE_ALL_PERCENT { get; set; }
        public Nullable<double> SUP_EPP { get; set; }
        public Nullable<double> SUP_CPP { get; set; }
        public Nullable<double> SUP_INT { get; set; }
        public Nullable<double> SUP_OTHER { get; set; }
        public Nullable<double> TOTAL_MAN_ALL { get; set; }
        public Nullable<double> POST_ALL_AMOUNT { get; set; }
        public Nullable<double> AVAILABLE_BAL { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_DATE { get; set; }
        public string APPROVAL_STATUS { get; set; }
        public string REMARKS { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
        public string ATTRIBUTE6 { get; set; }
        public string ATTRIBUTE7 { get; set; }
        public string ATTRIBUTE8 { get; set; }
        public string ATTRIBUTE9 { get; set; }
        public string ATTRIBUTE10 { get; set; }
        public Nullable<double> ORGANIZATION_ID { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<double> CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public Nullable<double> LAST_UPDATED_BY { get; set; }
        public Nullable<double> LAST_UPDATE_LOGIN { get; set; }
        public Nullable<double> HEADER_ID_FK { get; set; }
        public Nullable<double> AVAIL_EPP { get; set; }
        public Nullable<double> AVAIL_CPP { get; set; }
        public Nullable<double> AVAIL_INT { get; set; }
        public Nullable<double> AVAIL_OTHER { get; set; }
        public Nullable<double> AVAIL_TOTAL { get; set; }
        public Nullable<double> OUT_EPP { get; set; }
        public Nullable<double> OUT_CPP { get; set; }
        public Nullable<double> OUT_INT { get; set; }
        public Nullable<double> OUT_OTHER { get; set; }
        public Nullable<double> ALLOC_EPP { get; set; }
        public Nullable<double> ALLOC_CPP { get; set; }
        public Nullable<double> ALLOC_INT { get; set; }
        public Nullable<double> ALLOC_OTHER { get; set; }
        public Nullable<double> ALLOC_TOTAL { get; set; }
        public Nullable<double> VENDOR_SITE_ID { get; set; }
        public string VENDOR_SITE_CODE { get; set; }
    }
}
